# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bc217d0b55a533859845bd34487a485da372bd60d6e02df6600d4363c40fff6cdea9c9cb41807f49613c96253265219402a39e1a8cea989546cf1451110edfec

test:
  secret_key_base: 7e4c9fa038f08fe11a4364a79b3f6901d36e810920ab711516835b6160048c6792203e98c1c279d1848d79a75525539e5fde2c82e8c79c9f6fd381e970d9e5e7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
